import { type FormEvent, useCallback, useEffect, useState } from 'react'
import { Database, Plus, Search, X } from 'lucide-react'
import { ApiError, api } from '../../api/client'

const types = ['TITLE', 'COUNTRY', 'PROVINCE', 'DISTRICT', 'SUBDISTRICT', 'POSTAL_CODE', 'TENANT_TYPE', 'ACADEMIC_YEAR', 'RENTAL_PERIOD', 'CONTRACT_TYPE', 'FACULTY', 'MAJOR', 'FEE_TYPE'] as const
type MasterDataType = typeof types[number]
type Item = { id: number; type: MasterDataType; code: string; nameTh: string; nameEn: string | null; parentId: number | null; effectiveFrom: string; effectiveTo: string | null; active: boolean; deactivationReason: string | null; version: number }
type Page = { content: Item[]; number: number; totalElements: number; totalPages: number; size: number }
type Dialog = { kind: 'edit'; item: Item } | { kind: 'create' } | { kind: 'status'; item: Item } | null

export function MasterDataPage() {
  const [type, setType] = useState<MasterDataType>('FEE_TYPE'); const [query, setQuery] = useState(''); const [draftQuery, setDraftQuery] = useState(''); const [data, setData] = useState<Page | null>(null); const [loading, setLoading] = useState(true); const [error, setError] = useState(''); const [dialog, setDialog] = useState<Dialog>(null)
  const load = useCallback(async () => { setLoading(true); setError(''); const params = new URLSearchParams({ page: '0', size: '50', sort: 'code,asc' }); if (query) params.set('query', query); try { setData(await api.get<Page>(`/api/v1/master-data/${type}?${params}`)) } catch (cause) { setError(cause instanceof Error ? cause.message : 'โหลดข้อมูลตั้งต้นไม่สำเร็จ') } finally { setLoading(false) } }, [query, type])
  useEffect(() => { void load() }, [load])
  function replace(item: Item) { setData((current) => current ? { ...current, content: current.content.map((value) => value.id === item.id ? item : value) } : current) }
  function add(item: Item) { setData((current) => current ? { ...current, totalElements: current.totalElements + 1, content: [...current.content, item].sort((a, b) => a.code.localeCompare(b.code)) } : current) }
  return <div className="content admin-page"><section className="page-intro"><div><p className="eyebrow">MASTER DATA · EFFECTIVE DATED</p><h1>ข้อมูลตั้งต้น</h1><p>ทุกการเปลี่ยนแปลงมีช่วงวันที่ใช้งานและตรวจสอบย้อนหลังได้</p></div><button className="primary-action" onClick={() => setDialog({ kind: 'create' })}><Plus size={17} /> เพิ่มรายการ</button></section><section className="operations-rail master-rail"><label className="type-select"><Database size={16} /><select aria-label="ประเภทข้อมูล" value={type} onChange={(event) => { setType(event.target.value as MasterDataType); setQuery(''); setDraftQuery('') }}>{types.map((value) => <option key={value}>{value}</option>)}</select></label><form className="operations-rail__search" onSubmit={(event) => { event.preventDefault(); setQuery(draftQuery.trim()) }}><label><Search size={16} /><input aria-label="ค้นหาข้อมูลตั้งต้น" value={draftQuery} onChange={(event) => setDraftQuery(event.target.value)} placeholder="รหัสหรือชื่อ" /></label><button>ค้นหา</button></form><span>{data?.totalElements || 0} รายการ</span></section>{loading ? <section className="panel state-panel" role="status">กำลังโหลดข้อมูล…</section> : error ? <section className="panel state-panel" role="alert">{error}</section> : data?.content.length === 0 ? <section className="panel state-panel"><Database size={26} /><b>ยังไม่มีข้อมูลประเภทนี้</b><p>เพิ่มรายการแรกเพื่อเริ่มใช้งาน</p></section> : <section className="data-panel"><div className="data-table"><div className="data-row data-row--header master-row"><span>รหัส / ชื่อ</span><span>ช่วงที่มีผล</span><span>สถานะ</span><span>การจัดการ</span></div>{data?.content.map((item) => <div className="data-row master-row" key={item.id}><span data-label="รหัส / ชื่อ"><b><code>{item.code}</code> · {item.nameTh}</b><small>{item.nameEn || '—'}</small></span><span data-label="ช่วงที่มีผล"><b>{thaiDate(item.effectiveFrom)}</b><small>ถึง {item.effectiveTo ? thaiDate(item.effectiveTo) : 'ไม่มีกำหนด'}</small></span><span data-label="สถานะ"><i className={`status-chip ${item.active ? 'status-chip--active' : 'status-chip--inactive'}`}>{item.active ? 'ใช้งาน' : 'ปิดใช้งาน'}</i></span><span className="row-actions" data-label="การจัดการ"><button onClick={() => setDialog({ kind: 'edit', item })}>แก้ไข</button><button aria-label={`${item.active ? 'ปิด' : 'เปิด'}ใช้งาน ${item.code}`} onClick={() => setDialog({ kind: 'status', item })}>{item.active ? 'ปิดใช้งาน' : 'เปิดใช้งาน'}</button></span></div>)}</div></section>}{dialog?.kind === 'status' ? <StatusDialog item={dialog.item} close={() => setDialog(null)} saved={(item) => { replace(item); setDialog(null) }} /> : dialog ? <ItemDialog type={type} item={dialog.kind === 'edit' ? dialog.item : undefined} close={() => setDialog(null)} saved={(item) => { dialog.kind === 'create' ? add(item) : replace(item); setDialog(null) }} /> : null}</div>
}

function ItemDialog({ type, item, close, saved }: { type: MasterDataType; item?: Item; close: () => void; saved: (item: Item) => void }) {
  const [error, setError] = useState('')
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const form = new FormData(event.currentTarget); const body = { code: form.get('code'), nameTh: form.get('nameTh'), nameEn: form.get('nameEn') || null, parentId: form.get('parentId') ? Number(form.get('parentId')) : null, effectiveFrom: form.get('effectiveFrom'), effectiveTo: form.get('effectiveTo') || null, ...(item ? { version: item.version } : {}) }; try { saved(item ? await api.put<Item>(`/api/v1/master-data/${type}/${item.id}`, body) : await api.post<Item>(`/api/v1/master-data/${type}`, body)) } catch (cause) { setError(cause instanceof ApiError && cause.status === 409 ? 'ข้อมูลถูกแก้ไขโดยผู้ใช้อื่น กรุณาปิดหน้าต่างและโหลดใหม่' : cause instanceof Error ? cause.message : 'บันทึกไม่สำเร็จ') } }
  return <div className="dialog-backdrop"><section className="admin-dialog" role="dialog" aria-modal="true"><button className="dialog-close" aria-label="ปิด" onClick={close}><X size={18} /></button><h2>{item ? `แก้ไข ${item.code}` : `เพิ่ม ${type}`}</h2><form className="admin-form" onSubmit={submit}><label>รหัส<input name="code" defaultValue={item?.code} maxLength={40} required /></label><label>ชื่อภาษาไทย<input name="nameTh" defaultValue={item?.nameTh} maxLength={200} required /></label><label>ชื่อภาษาอังกฤษ<input name="nameEn" defaultValue={item?.nameEn || ''} maxLength={200} /></label><label>รหัสรายการแม่<input name="parentId" type="number" defaultValue={item?.parentId || ''} /></label><label>วันที่เริ่มใช้<input name="effectiveFrom" type="date" defaultValue={item?.effectiveFrom} required /></label><label>วันที่สิ้นสุด<input name="effectiveTo" type="date" defaultValue={item?.effectiveTo || ''} /></label>{error && <p role="alert" className="form-error">{error}</p>}<button className="primary-action">บันทึกรายการ</button></form></section></div>
}
function StatusDialog({ item, close, saved }: { item: Item; close: () => void; saved: (item: Item) => void }) { const [error, setError] = useState(''); async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const reason = new FormData(event.currentTarget).get('reason'); try { saved(await api.patch<Item>(`/api/v1/master-data/${item.type}/${item.id}/status`, { active: !item.active, reason, version: item.version })) } catch (cause) { setError(cause instanceof Error ? cause.message : 'เปลี่ยนสถานะไม่สำเร็จ') } } return <div className="dialog-backdrop"><section className="admin-dialog" role="dialog" aria-modal="true"><button className="dialog-close" aria-label="ปิด" onClick={close}><X size={18} /></button><h2>{item.active ? 'ปิด' : 'เปิด'}ใช้งาน {item.code}</h2><form className="admin-form" onSubmit={submit}><label>เหตุผล<textarea name="reason" aria-label="เหตุผล" required /></label>{error && <p role="alert" className="form-error">{error}</p>}<button className="primary-action">ยืนยันเปลี่ยนสถานะ</button></form></section></div> }
function thaiDate(value: string) { const [year, month, day] = value.split('-').map(Number); return new Intl.DateTimeFormat('th-TH', { day: 'numeric', month: 'short', year: 'numeric' }).format(new Date(year, month - 1, day)) }
