package th.ac.dusit.dorm.platform;

import static org.assertj.core.api.Assertions.assertThat;
import static org.springframework.security.test.web.servlet.request.SecurityMockMvcRequestPostProcessors.csrf;
import static org.springframework.security.test.web.servlet.request.SecurityMockMvcRequestPostProcessors.user;
import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.get;
import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.post;
import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.header;
import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.jsonPath;
import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.status;

import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.boot.webmvc.test.autoconfigure.AutoConfigureMockMvc;
import org.springframework.http.MediaType;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.test.web.servlet.MockMvc;

@SpringBootTest(properties = "DORM_BOOTSTRAP_PASSWORD=Admin@1234")
@AutoConfigureMockMvc
class PlatformInfrastructureIntegrationTest {

    @Autowired
    private MockMvc mockMvc;

    @Autowired
    private JdbcTemplate jdbcTemplate;

    @Test
    void everyHttpResponseCarriesATraceId() throws Exception {
        mockMvc.perform(get("/actuator/health"))
                .andExpect(status().isOk())
                .andExpect(header().exists("X-Trace-Id"));
    }

    @Test
    void exposesOpenApiDocumentation() throws Exception {
        mockMvc.perform(get("/v3/api-docs").with(user("admin").roles("ADMIN")))
                .andExpect(status().isOk())
                .andExpect(jsonPath("$.info.title").value("Dormitory Management API"));
    }

    @Test
    void protectsOpenApiDocumentationFromAnonymousUsers() throws Exception {
        mockMvc.perform(get("/v3/api-docs"))
                .andExpect(status().isUnauthorized());
    }

    @Test
    void successfulLoginCreatesAnAuditEntry() throws Exception {
        jdbcTemplate.execute("""
                CREATE TABLE IF NOT EXISTS audit_logs (
                    audit_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    actor VARCHAR(80) NOT NULL,
                    action VARCHAR(80) NOT NULL,
                    entity_type VARCHAR(80) NOT NULL,
                    entity_id VARCHAR(80),
                    reason VARCHAR(500),
                    ip_address VARCHAR(64),
                    trace_id VARCHAR(64),
                    details VARCHAR(2000),
                    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
                )
                """);
        jdbcTemplate.update("DELETE FROM audit_logs");

        mockMvc.perform(post("/api/v1/auth/login")
                        .with(csrf())
                        .contentType(MediaType.APPLICATION_JSON)
                        .content("{\"username\":\"admin\",\"password\":\"Admin@1234\"}"))
                .andExpect(status().isOk());

        var actions = jdbcTemplate.queryForList(
                "SELECT action FROM audit_logs WHERE actor = ?", String.class, "admin");
        assertThat(actions).contains("LOGIN_SUCCESS");
    }
}
