import { type FormEvent, useCallback, useEffect, useState } from 'react'
import { FileClock, Search } from 'lucide-react'
import { api } from '../../api/client'

type AuditLog = { id: number; actor: string; action: string; entityType: string; entityId: string | null; reason: string | null; ipAddress: string | null; traceId: string; details: Record<string, unknown>; createdAt: string }
type AuditPageResponse = { content: AuditLog[]; number: number; totalElements: number; totalPages: number; size: number }
type Filters = { actor: string; action: string; entityType: string; from: string; to: string }
const emptyFilters: Filters = { actor: '', action: '', entityType: '', from: '', to: '' }

export function AuditPage() {
  const [draft, setDraft] = useState(emptyFilters); const [filters, setFilters] = useState(emptyFilters); const [data, setData] = useState<AuditPageResponse | null>(null); const [page, setPage] = useState(0); const [loading, setLoading] = useState(true); const [error, setError] = useState('')
  const load = useCallback(async () => { setLoading(true); setError(''); const params = new URLSearchParams({ page: String(page), size: '20', sort: 'createdAt,desc' }); Object.entries(filters).forEach(([key, value]) => { if (value) params.set(key, value) }); try { setData(await api.get<AuditPageResponse>(`/api/v1/audit-logs?${params}`)) } catch (cause) { setError(cause instanceof Error ? cause.message : 'โหลดประวัติไม่สำเร็จ') } finally { setLoading(false) } }, [filters, page])
  useEffect(() => { void load() }, [load])
  function submit(event: FormEvent) { event.preventDefault(); setPage(0); setFilters(draft) }
  return <div className="content admin-page"><section className="page-intro"><div><p className="eyebrow">AUDIT · READ ONLY</p><h1>ประวัติการใช้งาน</h1><p>ตรวจสอบผู้ดำเนินการ เหตุการณ์ และรหัสติดตามย้อนหลัง</p></div></section><section className="operations-rail audit-rail"><form onSubmit={submit}><label><Search size={16} /><input aria-label="ผู้ดำเนินการ" placeholder="ผู้ดำเนินการ" value={draft.actor} onChange={(event) => setDraft({ ...draft, actor: event.target.value })} /></label><label><input aria-label="การกระทำ" placeholder="การกระทำ" value={draft.action} onChange={(event) => setDraft({ ...draft, action: event.target.value })} /></label><label><input aria-label="ประเภทข้อมูล" placeholder="ประเภทข้อมูล" value={draft.entityType} onChange={(event) => setDraft({ ...draft, entityType: event.target.value })} /></label><button>กรองข้อมูล</button></form><span>{data?.totalElements || 0} เหตุการณ์</span></section>{loading ? <section className="panel state-panel" role="status">กำลังโหลดประวัติ…</section> : error ? <section className="panel state-panel" role="alert">{error}</section> : data?.content.length === 0 ? <section className="panel state-panel"><FileClock size={26} /><b>ไม่พบเหตุการณ์</b><p>ลองปรับตัวกรองให้กว้างขึ้น</p></section> : <section className="data-panel"><div className="audit-list">{data?.content.map((entry) => <article className="audit-entry" key={entry.id}><time>{dateTime(entry.createdAt)}</time><span className="audit-entry__signal" /><div><div className="audit-entry__title"><code>{entry.action}</code><i>{entry.entityType}{entry.entityId ? ` #${entry.entityId}` : ''}</i></div><p><b>{entry.actor}</b>{entry.ipAddress ? ` · ${entry.ipAddress}` : ''}{entry.reason ? ` · ${entry.reason}` : ''}</p><details><summary>รายละเอียดและ trace ID</summary><code>{entry.traceId}</code><pre>{JSON.stringify(entry.details, null, 2)}</pre></details></div></article>)}</div><div className="pagination"><button disabled={page === 0} onClick={() => setPage((value) => value - 1)}>ก่อนหน้า</button><span>หน้า {page + 1} / {Math.max(data?.totalPages || 1, 1)}</span><button disabled={!data || page + 1 >= data.totalPages} onClick={() => setPage((value) => value + 1)}>ถัดไป</button></div></section>}</div>
}
function dateTime(value: string) { return new Intl.DateTimeFormat('th-TH', { dateStyle: 'medium', timeStyle: 'short' }).format(new Date(value)) }
