import { useEffect, useMemo, useState } from 'react'
import { Save, ShieldCheck } from 'lucide-react'
import { api } from '../../api/client'

type Role = { code: string; nameTh: string; description: string | null; active: boolean; version: number; permissions: string[] }

export function RolesPage() {
  const [roles, setRoles] = useState<Role[]>([]); const [selectedCode, setSelectedCode] = useState(''); const [permissions, setPermissions] = useState<string[]>([]); const [reason, setReason] = useState(''); const [error, setError] = useState(''); const [message, setMessage] = useState(''); const [loading, setLoading] = useState(true)
  useEffect(() => { api.get<Role[]>('/api/v1/roles').then((items) => { setRoles(items); if (items[0]) { setSelectedCode(items[0].code); setPermissions(items[0].permissions) } }).catch((cause) => setError(cause instanceof Error ? cause.message : 'โหลดบทบาทไม่สำเร็จ')).finally(() => setLoading(false)) }, [])
  const selected = roles.find((role) => role.code === selectedCode)
  const permissionCatalog = useMemo(() => Array.from(new Set(roles.flatMap((role) => role.permissions))).sort(), [roles])
  function choose(role: Role) { setSelectedCode(role.code); setPermissions(role.permissions); setReason(''); setMessage(''); setError('') }
  function toggle(code: string) { setPermissions((current) => current.includes(code) ? current.filter((item) => item !== code) : [...current, code]) }
  async function save() { if (!selected || !reason.trim()) return; setError(''); setMessage(''); try { const updated = await api.put<Role>(`/api/v1/roles/${selected.code}/permissions`, { permissions, reason }); setRoles((current) => current.map((role) => role.code === updated.code ? updated : role)); setPermissions(updated.permissions); setReason(''); setMessage('บันทึกสิทธิ์แล้ว') } catch (cause) { setError(cause instanceof Error ? cause.message : 'บันทึกสิทธิ์ไม่สำเร็จ') } }
  return <div className="content admin-page"><section className="page-intro"><div><p className="eyebrow">IDENTITY · RBAC</p><h1>สิทธิ์การใช้งาน</h1><p>ตรวจสอบและกำหนดขอบเขตงานของแต่ละบทบาท</p></div></section>{loading ? <section className="panel state-panel" role="status">กำลังโหลดบทบาท…</section> : error && roles.length === 0 ? <section className="panel state-panel" role="alert">{error}</section> : <section className="role-workspace"><aside className="role-list" aria-label="บทบาท">{roles.map((role) => <button key={role.code} className={selectedCode === role.code ? 'role-card role-card--active' : 'role-card'} onClick={() => choose(role)}><ShieldCheck size={18} /><span><b>{role.nameTh}</b><small>{role.code}</small></span><i>{role.permissions.length}</i></button>)}</aside><article className="panel permission-panel">{selected && <><div className="panel__heading"><div><p className="eyebrow">{selected.code}</p><h2>{selected.nameTh}</h2><p>{selected.description}</p></div><i className={`status-chip ${selected.active ? 'status-chip--active' : 'status-chip--inactive'}`}>{selected.active ? 'ใช้งาน' : 'ปิดใช้งาน'}</i></div><div className="permission-grid">{permissionCatalog.map((code) => <label key={code}><input type="checkbox" aria-label={code} checked={permissions.includes(code)} onChange={() => toggle(code)} /><span><code>{code}</code><small>{permissionLabel(code)}</small></span></label>)}</div><label className="reason-field">เหตุผลการเปลี่ยนสิทธิ์<textarea value={reason} onChange={(event) => setReason(event.target.value)} required /></label>{error && <p role="alert" className="form-error">{error}</p>}{message && <p role="status" className="form-success">{message}</p>}<button className="primary-action" disabled={!reason.trim() || permissions.length === 0} onClick={save}><Save size={16} /> บันทึกสิทธิ์</button></>}</article></section>}</div>
}
function permissionLabel(code: string) { const [resource, action] = code.split(':'); return `${action === 'READ' ? 'ดูข้อมูล' : 'ทำรายการ'} ${resource.replaceAll('_', ' ').toLowerCase()}` }
